name: Publish to Docker

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: pjamroziak/unsold-food-deals-api:latest